#!/usr/bin/python3

import argparse, requests, re

parser = argparse.ArgumentParser()
parser.add_argument("-o", "--org", required=True, help="organização, ex: --org yahoo")
parser.add_argument("-A", "--user_agent", help="coloque o user-agent (não obrigatório)")
args = parser.parse_args()

org = args.org
agent = args.user_agent

if agent:
        headers = {"User-agent": agent}
else:
        headers = {
                "User-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0"
        }

url = f"https://bgp.he.net/search?search%5Bsearch%5D={org}&commit=Search"
req = requests.get(url).text

regex = "AS[0-9]{5}"
asns = re.findall(regex, req)
asns = "\n".join(asns)
print(asns)
